---
title: "plotly question"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(flexdashboard)
library(tidyverse)
library(p8105.datasets)
library(plotly)
```


```{r}
data(instacart)
```

```{r}
instacart=instacart|>
  janitor::clean_names()|>
  drop_na()
```




-----------------------------------------------------------------------

### A Box Plot about Fresh Fruits and Fresh Vegetables

```{r}
instacart |>
  plot_ly(x= ~department, y = ~order_hour_of_day, color = ~department, type = "box", colors = "viridis")

 
```



-----------------------------------------------------------------------

## Number of Items in Each Aisle via Scatterplot

```{r}
aisle_graph=instacart|>
  count(aisle,name="n_items")|>
  filter(n_items>10000)|>
  mutate(aisle=fct_reorder(aisle,n_items))|>
  ggplot(aes(x=aisle,y=n_items))+
  geom_point()+
  theme(axis.text.x = element_text(angle = 65, vjust = 1, hjust=1))+
  ggtitle("Number of Items in Each Aisle")
  
ggplotly(aisle_graph)
  
  
```


-----------------------------------------------------------------------

### Bar Chart of Top 10 Product Reordered

```{r}
instacart |> 
  filter(reordered%in%1)|>
  count(product_name) |> 
  arrange(desc(n))|>
  head(10)|>
  mutate(product_name = fct_reorder(product_name, n)) |> 
  plot_ly(x = ~product_name, y = ~n, color = ~product_name, type = "bar", colors = "viridis")
```



